/**
 * Code and Template Generator for Missing Audit Items
 * Automatically produces copy-paste ready fixes for developers and store owners.
 */

function generateLlmsTxt(siteInfo = {}) {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'E-Ticaret Mağazası';
  const desc = siteInfo.description || 'Yüksek kaliteli ürünler ve hızlı kargo avantajı sunan e-ticaret platformu.';
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';

  return `# ${brandName} - AI & LLM Rehberi (llms.txt)
> ${desc}

## Hakkımızda ve Temel Bilgiler
- [Hakkımızda](${domain}/hakkimizda): Şirket profili, misyon ve değerler
- [İletişim ve Destek](${domain}/iletisim): Müşteri hizmetleri ve iletişim kanalları
- [Sıkça Sorulan Sorular](${domain}/sss): Sipariş, kargo ve ödeme rehberi

## Ürün ve Hizmet Kategorileri
- [Tüm Ürünler](${domain}/urunler): Güncel ürün kataloğu
- [Kampanyalar & İndirimler](${domain}/kampanyalar): Aktif promosyonlar

## Yasal ve Müşteri Hakları
- [Mesafeli Satış Sözleşmesi](${domain}/mesafeli-satis-sozlesmesi): Yasal satış şartları
- [İade ve Değişim Koşulları](${domain}/iade-kosullari): 14 gün cayma hakkı ve iade prosedürü
- [Gizlilik ve KVKK Politikası](${domain}/kvkk): Kişisel verilerin korunması kanunu aydınlatma metni
`;
}

function generateRobotsTxt(siteInfo = {}) {
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';
  return `# robots.txt generated by PreCheckout Audit Suite
User-agent: *
Disallow: /admin/
Disallow: /checkout/
Disallow: /cart/
Disallow: /sepet/
Disallow: /odeme/
Disallow: /hesabim/
Disallow: /my-account/
Disallow: /*?*filter=
Disallow: /*?*sort=

# Sitemap tanımı
Sitemap: ${domain}/sitemap.xml
`;
}

function generateFaqSchema(siteInfo = {}) {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'Mağazamız';
  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "Siparişim ne kadar sürede kargoya verilir?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": `${brandName} üzerinden saat 15:00'e kadar verilen tüm siparişler aynı gün anlaşmalı kargo firmalarına teslim edilir. Ortalama teslimat süresi 1-3 iş günüdür.`
        }
      },
      {
        "@type": "Question",
        "name": "Hangi ödeme yöntemlerini kabul ediyorsunuz?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Tüm kredi kartlarına peşin fiyatına taksit, banka kartı, Havale/EFT ve 3D Secure güvenli ödeme altyapısıyla işlem yapabilirsiniz."
        }
      },
      {
        "@type": "Question",
        "name": "Satın aldığım ürünü nasıl iade edebilirim?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Teslimat tarihinden itibaren 14 gün içerisinde herhangi bir gerekçe göstermeksizin ücretsiz iade kargo kodu oluşturarak ürünü iade edebilirsiniz."
        }
      },
      {
        "@type": "Question",
        "name": "Kargo ücreti ne kadar?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Belirli tutarın üzerindeki tüm siparişlerinizde kargo tamamen ücretsizdir. Bu tutarın altındaki siparişler için standart sabit kargo bedeli uygulanır."
        }
      },
      {
        "@type": "Question",
        "name": "Ürünler orijinal ve garantili mi?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Sitemizde satışa sunulan tüm ürünler %100 orijinal olup en az 24 ay resmi distribütör/üretici garantisi kapsamındadır."
        }
      }
    ]
  };

  return `<script type="application/ld+json">\n${JSON.stringify(schema, null, 2)}\n</script>`;
}

function generateBreadcrumbSnippet(siteInfo = {}) {
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';
  const schema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Ana Sayfa",
        "item": domain
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Kategori Adı",
        "item": `${domain}/kategori-adi`
      },
      {
        "@type": "ListItem",
        "position": 3,
        "name": "Ürün Adı",
        "item": `${domain}/kategori-adi/urun-adi`
      }
    ]
  };

  const html = `<!-- Breadcrumb HTML Navigasyonu -->
<nav aria-label="breadcrumb" class="breadcrumb-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="${domain}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="${domain}/kategori-adi">Kategori Adı</a></li>
    <li class="breadcrumb-item active" aria-current="page">Ürün Adı</li>
  </ol>
</nav>

<!-- BreadcrumbList Schema JSON-LD -->
<script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
</script>`;

  return html;
}

function generateSocialMeta(siteInfo = {}) {
  const title = siteInfo.title || 'Mağaza Adı - Güvenli E-Ticaret';
  const desc = siteInfo.description || 'En yeni ürünler, avantajlı fiyatlar ve hızlı kargo fırsatları ile hemen keşfedin.';
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';

  return `<!-- Open Graph / Facebook / WhatsApp -->
<meta property="og:type" content="website" />
<meta property="og:url" content="${domain}" />
<meta property="og:title" content="${title}" />
<meta property="og:description" content="${desc}" />
<meta property="og:image" content="${domain}/assets/og-image.jpg" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:url" content="${domain}" />
<meta name="twitter:title" content="${title}" />
<meta name="twitter:description" content="${desc}" />
<meta name="twitter:image" content="${domain}/assets/og-image.jpg" />
`;
}

function generateStickyPhoneHtml() {
  return `<!-- Sabit Telefon & WhatsApp Hızlı CTA Butonu (Mobil & Masaüstü) -->
<style>
  .precheck-floating-cta {
    position: fixed;
    bottom: 24px;
    right: 24px;
    z-index: 99999;
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .precheck-btn-call, .precheck-btn-wa {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 12px 18px;
    border-radius: 50px;
    color: #fff;
    text-decoration: none;
    font-weight: 600;
    font-size: 14px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.25);
    transition: transform 0.2s ease;
  }
  .precheck-btn-call { background-color: #2563eb; }
  .precheck-btn-wa { background-color: #22c55e; }
  .precheck-btn-call:hover, .precheck-btn-wa:hover { transform: scale(1.05); }
</style>

<div class="precheck-floating-cta">
  <a href="https://wa.me/905550000000?text=Merhaba,%20siparişimle%20ilgili%20bilgi%20almak%20istiyorum." target="_blank" rel="noopener noreferrer" class="precheck-btn-wa">
    <span>💬 WhatsApp Sipariş</span>
  </a>
  <a href="tel:08500000000" class="precheck-btn-call">
    <span>📞 Hemen Ara</span>
  </a>
</div>`;
}

function generateLegalTemplates(siteInfo = {}) {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : '[Şirket Ticari Unvanı]';
  return {
    mesafeliSatis: `# MESAFELİ SATIŞ SÖZLEŞMESİ

MADDE 1 - TARAFLAR
SATICI: ${brandName}
Adres: [Şirket Açık Adresi]
Telefon: [Telefon Numarası]
E-posta: [E-posta Adresi]
MERSİS No: [Mersis No]

ALICI: Müşteri (Sipariş esnasında girilen bilgiler)

MADDE 2 - SÖZLEŞMENİN KONUSU
İşbu Sözleşme, ALICI'nın SATICI'ya ait internet sitesinden elektronik ortamda siparişini verdiği ürünün satışı ve teslimi ile ilgili 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler Yönetmeliği hükümleri gereğince tarafların hak ve yükümlülüklerini kapsar.

MADDE 3 - CAYMA HAKKI
ALICI, hiçbir hukuki ve cezai sorumluluk üstlenmeksizin ve hiçbir gerekçe göstermeksizin, mal teslimine ilişkin sözleşmelerde malı teslim aldığı tarihten itibaren 14 (on dört) gün içerisinde cayma hakkını kullanabilir.`,

    kvkk: `# KİŞİSEL VERİLERİN KORUNMASI AYDINLATMA METNİ

${brandName} olarak kişisel verilerinizin güvenliği ve gizliliği hususuna azami hassasiyet göstermekteyiz. 6698 sayılı Kişisel Verilerin Korunması Kanunu ("KVKK") uyarınca, veri sorumlusu sıfatıyla tarafımıza iletmiş olduğunuz kişisel verileriniz:
- Siparişlerinizin tamamlanması ve teslimat süreçlerinin yürütülmesi,
- Yasal fatura ve muhasebe yükümlülüklerinin yerine getirilmesi,
- İzniniz dahilinde kampanya ve duyuruların paylaşılması amacıyla işlenmektedir.`
  };
}

// --- Platform-aware install note helper ---
function platformNote(platform, notes) {
  const key = (platform || 'generic').toLowerCase();
  return notes[key] || notes.generic;
}

function generate404Page(siteInfo = {}, platform = 'generic') {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'Mağazamız';
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';

  const html = `<!-- Özel 404 Sayfası (Satışa Yönlendiren) -->
<div class="precheck-404-page" style="max-width:640px;margin:80px auto;text-align:center;font-family:sans-serif;">
  <h1 style="font-size:72px;margin:0;color:#111;">404</h1>
  <h2 style="font-size:22px;margin:8px 0 16px;">Aradığınız sayfa bulunamadı</h2>
  <p style="color:#666;margin-bottom:24px;">Ürün kaldırılmış ya da adres değişmiş olabilir. Aramaya devam edin veya anasayfaya dönün.</p>
  <form action="${domain}/arama" method="get" style="display:flex;gap:8px;max-width:360px;margin:0 auto 20px;">
    <input type="text" name="q" placeholder="Ne aramıştınız?" style="flex:1;padding:10px 14px;border:1px solid #ddd;border-radius:8px;">
    <button type="submit" style="padding:10px 18px;background:#111;color:#fff;border:0;border-radius:8px;">Ara</button>
  </form>
  <a href="${domain}" style="display:inline-block;padding:10px 22px;background:#2563eb;color:#fff;border-radius:8px;text-decoration:none;font-weight:600;">${brandName} Anasayfasına Dön</a>
  <div style="margin-top:28px;font-size:13px;color:#999;">Popüler kategoriler: <a href="${domain}/urunler">Tüm Ürünler</a> · <a href="${domain}/kampanyalar">Kampanyalar</a></div>
</div>`;

  const install = platformNote(platform, {
    shopify: 'Shopify: Online Store → Themes → Edit Code → templates/404.liquid dosyasını açıp içeriği bu HTML ile değiştirin (Liquid nesnelerini {{ }} formatında ekleyebilirsiniz).',
    woocommerce: 'WooCommerce: Tema klasörünüzde 404.php dosyasını (yoksa oluşturun) düzenleyip bu HTML bloğunu get_header()/get_footer() arasına yerleştirin.',
    ticimax: 'Ticimax: Yönetim Paneli → Tasarım → Sayfa Tasarımı → "404 Sayfası" bölümünden HTML içeriği bu kod ile güncelleyin.',
    ikas: 'İkas: Mağaza Yönetimi → Tema → Sayfalar → 404 Sayfası özel içerik alanına bu HTML\'i yapıştırın.',
    generic: 'Sitenizin 404 şablon dosyasına (genelde 404.html / 404.php / 404.liquid) bu bloğu yerleştirin.'
  });

  return `${html}\n\n<!-- Kurulum Notu (${platform || 'genel'}): ${install} -->`;
}

function generateTopCtaBanner(siteInfo = {}, platform = 'generic') {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'Mağazamız';
  const html = `<!-- Üst Kısım Sabit CTA / Duyuru Şeridi -->
<div class="precheck-top-cta" style="background:#111;color:#fff;text-align:center;padding:10px 16px;font-size:13px;font-weight:600;">
  🚚 ${brandName}'da 500₺ üzeri siparişlerde kargo ücretsiz! <a href="/kampanyalar" style="color:#7dd3fc;text-decoration:underline;margin-left:6px;">Hemen İncele →</a>
</div>`;

  const install = platformNote(platform, {
    shopify: 'Shopify: theme.liquid dosyasında <body> etiketinin hemen altına ekleyin; header bölümünün sticky olması için tema ayarlarından "Sticky header" seçeneğini açın.',
    woocommerce: 'WooCommerce: header.php dosyasında <body> açıldıktan hemen sonra ekleyin veya bir "Header/Footer" eklentisiyle enjekte edin.',
    ticimax: 'Ticimax: Tasarım → Üst Bilgi (Header) alanına özel HTML modülü olarak ekleyin.',
    ikas: 'İkas: Tema Düzenleyici → Header bileşenleri → Özel HTML bloğu ile ekleyin.',
    generic: 'Sitenizin header/nav bileşeninin en üstüne, tüm sayfalarda görünecek şekilde ekleyin.'
  });

  return `${html}\n\n<!-- Kurulum Notu (${platform || 'genel'}): ${install} -->`;
}

function generateInternalLinkingGuide(siteInfo = {}) {
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';
  return `# İç Linkleme (Internal Linking) Aksiyon Rehberi

1. Her ürün sayfasının altına "Bunlar da İlginizi Çekebilir" bloğu ekleyin (aynı kategoriden 4-6 ürün).
2. Kategori sayfalarından alt kategorilere ve öne çıkan ürünlere link verin.
3. Blog/SSS içeriklerinden ilgili ürün/kategori sayfalarına en az 1-2 bağlantı ekleyin.
4. Footer'da en çok satan kategorilere kısayol linkleri bulundurun.

## Örnek "İlgili Ürünler" HTML Bloğu
<section class="precheck-related-products" style="margin-top:40px;">
  <h3>Bunlar da İlginizi Çekebilir</h3>
  <div style="display:flex;gap:16px;overflow-x:auto;">
    <a href="${domain}/urun/ornek-urun-1">Örnek Ürün 1</a>
    <a href="${domain}/urun/ornek-urun-2">Örnek Ürün 2</a>
    <a href="${domain}/urun/ornek-urun-3">Örnek Ürün 3</a>
  </div>
</section>

* Not: Çoğu e-ticaret alt yapısında (Shopify "related products" bloğu, WooCommerce "İlgili Ürünler" widget'ı, Ticimax/İkas "Çapraz Satış" modülü) bu özellik hazır gelir — sadece tema ayarlarından aktif edilmesi yeterlidir.`;
}

function generateThankYouPageSnippet(siteInfo = {}, platform = 'generic') {
  const html = `<!-- Teşekkür / Sipariş Onay Sayfası İçerik Bloğu -->
<div class="precheck-thankyou" style="max-width:560px;margin:60px auto;text-align:center;font-family:sans-serif;">
  <div style="font-size:48px;">✅</div>
  <h1 style="font-size:24px;margin:12px 0 6px;">Siparişiniz Alındı!</h1>
  <p style="color:#666;">Sipariş numaranız <strong>#{{order_number}}</strong>. Onay e-postası birazdan gelecek.</p>
  <a href="/hesabim/siparislerim" style="display:inline-block;margin-top:16px;padding:10px 20px;background:#2563eb;color:#fff;border-radius:8px;text-decoration:none;">Siparişimi Takip Et</a>
</div>`;

  const tracking = `\n<!-- Dönüşüm/Reklam Pikseli Örneği (Google Ads / Meta) -->\n<script>\n  // gtag('event', 'purchase', { value: {{order_total}}, currency: 'TRY', transaction_id: '{{order_number}}' });\n  // fbq('track', 'Purchase', { value: {{order_total}}, currency: 'TRY' });\n</script>`;

  const install = platformNote(platform, {
    shopify: 'Shopify: Settings → Checkout → "Additional scripts" veya checkout.liquid (Shopify Plus) alanına ekleyin; sipariş numarası/toplam için Liquid nesnelerini ({{ order.order_number }}) kullanın.',
    woocommerce: 'WooCommerce: "Order received" (thankyou) sayfası hook\'una (woocommerce_thankyou) bu bloğu ekleyin.',
    ticimax: 'Ticimax: Sipariş Tamamlandı sayfası şablonuna panel üzerinden bu HTML\'i ekleyin.',
    ikas: 'İkas: Sipariş Onay Sayfası tema bileşenine özel HTML/script alanından ekleyin.',
    generic: 'Sitenizin sipariş onay (thank you) sayfası şablonuna ekleyin.'
  });

  return `${html}${tracking}\n\n<!-- Kurulum Notu (${platform || 'genel'}): ${install} -->`;
}

function generateCaseStudyBlock(siteInfo = {}) {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'Mağazamız';
  return `<!-- Vaka Çalışması / Müşteri Referansı Bloğu -->
<section class="precheck-case-study" style="max-width:720px;margin:40px auto;padding:24px;border:1px solid #eee;border-radius:12px;">
  <h3 style="margin-top:0;">Başarı Hikayesi: [Müşteri Adı / Sektör]</h3>
  <p style="color:#555;">${brandName} ile çalışmaya başladıktan sonra [ölçülebilir sonuç, örn. "%40 daha hızlı teslimat" veya "aylık 200+ tekrar sipariş"] elde ettik.</p>
  <blockquote style="border-left:3px solid #2563eb;padding-left:12px;color:#333;font-style:italic;">"Ürün kalitesi ve müşteri desteği beklentimizin üzerindeydi." — Müşteri Adı, Unvan</blockquote>
</section>

* Not: Gerçek müşteri onayı olmadan vaka çalışması yayınlamayın; en az 2-3 tane gerçek referansla başlayın.`;
}

function generatePageSpeedGuide(siteInfo = {}) {
  return `# Site Hızı (Core Web Vitals) Aksiyon Listesi

1. **Görselleri optimize edin**: WebP/AVIF formatı kullanın, tüm <img> etiketlerine loading="lazy" ekleyin.
2. **Script'leri erteleyin**: Kritik olmayan JS dosyalarına defer/async ekleyin.
   <script src="/analytics.js" defer></script>
3. **Font yüklemeyi optimize edin**: font-display: swap; kullanın.
4. **Üçüncü parti script sayısını azaltın**: Chat widget, pop-up gibi araçları sayfa yüklendikten sonra tetikleyin.
5. **CDN kullanın**: Statik dosyaları (görsel, CSS, JS) bir CDN üzerinden servis edin.

## Hızlı Test
Google PageSpeed Insights (pagespeed.web.dev) üzerinden mobil skorunuzu ölçün; 90+ hedefleyin.`;
}

function generateMetaTitleGuide(siteInfo = {}) {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'Mağaza Adınız';
  return `<!-- Benzersiz Meta Başlık Şablonu -->
<title>{{Ürün/Kategori Adı}} | ${brandName} - Hızlı Kargo & Güvenli Ödeme</title>

# Kurallar
- 50-60 karakter arasında tutun.
- Her sayfada FARKLI bir başlık kullanın (aynı title'ı tekrar etmeyin).
- Ana anahtar kelimeyi başa yakın yerleştirin.
- Marka adını sonda kullanın.

## Örnek
<title>Oversize Keten Gömlek - Erkek | ${brandName}</title>`;
}

function generateMetaDescriptionGuide(siteInfo = {}) {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'Mağaza Adınız';
  return `<!-- Meta Açıklama Şablonu -->
<meta name="description" content="{{Ürün/Kategori Adı}} en uygun fiyatlarla ${brandName}'da! Aynı gün kargo, kapıda ödeme ve 14 gün ücretsiz iade avantajıyla hemen sipariş verin.">

# Kurallar
- 120-160 karakter arasında tutun.
- Harekete geçirici ifade kullanın (Hemen sipariş verin, Keşfedin, İncele).
- Kargo/iade/ödeme gibi güven unsurlarını vurgulayın.
- Her sayfada benzersiz olmalı.`;
}

function generateFastAuthButtons() {
  return `<!-- Hızlı Giriş / Üyelik Butonları -->
<div class="precheck-fast-auth" style="display:flex;gap:10px;max-width:320px;">
  <button style="flex:1;padding:10px;border-radius:8px;border:1px solid #ddd;background:#fff;display:flex;align-items:center;justify-content:center;gap:8px;">
    <span>🔵</span> Google ile Giriş
  </button>
  <button style="flex:1;padding:10px;border-radius:8px;border:1px solid #ddd;background:#fff;display:flex;align-items:center;justify-content:center;gap:8px;">
    <span>📱</span> SMS ile Giriş
  </button>
</div>

* Not: Üye ol/giriş formunu checkout akışının önüne zorunlu koymayın — "Üye Olmadan Devam Et (Misafir Alışverişi)" seçeneğini mutlaka bulundurun; sepet terkinin en yaygın nedenlerinden biridir.`;
}

function generateGoogleMapEmbed(siteInfo = {}) {
  const brandName = siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : 'Mağazamız';
  return `<!-- Google Harita Gömme & Açık Adres Bilgisi -->
<div class="precheck-map-address">
  <address style="font-style:normal;color:#333;margin-bottom:10px;">
    <strong>${brandName}</strong><br>
    [Cadde/Sokak No] [İlçe]/[Şehir] [Posta Kodu]<br>
    Tel: [Telefon Numarası]
  </address>
  <iframe
    src="https://www.google.com/maps?q={{Şirket+Açık+Adresi}}&output=embed"
    width="100%" height="280" style="border:0;border-radius:8px;" loading="lazy">
  </iframe>
</div>

* Not: {{Şirket+Açık+Adresi}} kısmını gerçek adresinizle değiştirip URL-encode edin. Footer ve İletişim sayfasında aynı adres bilgisinin görünmesi güven skorunu artırır.`;
}

function generateReviewsWidget(siteInfo = {}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Product",
    "name": "{{Ürün Adı}}",
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.8",
      "reviewCount": "124"
    }
  };
  return `<!-- Müşteri Yorumları Widget'ı + AggregateRating Schema -->
<section class="precheck-reviews">
  <h3>Müşteri Yorumları (4.8 / 5 — 124 Değerlendirme)</h3>
  <div class="review-item" style="border-bottom:1px solid #eee;padding:10px 0;">
    <strong>⭐⭐⭐⭐⭐ Müşteri Adı</strong>
    <p style="color:#555;margin:4px 0 0;">"Ürün açıklamasıyla birebir aynı, hızlı kargo."</p>
  </div>
</section>

<script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
</script>

* Not: Gerçek yorum toplamak için sipariş sonrası otomatik "Yorum Yap" e-postası gönderin (Shopify: Judge.me/Loox, WooCommerce: WooCommerce Reviews, Ticimax/İkas: hazır yorum modülü).`;
}

function generateImageAltGuide() {
  return `# Resim Alt Etiketi (Image Alt Tags) Aksiyon Rehberi

## Kural
Her <img> etiketine ürünü/ekran görüntüsünü açıklayan, anahtar kelime içeren ama doğal bir alt metni ekleyin.

## Kötü Örnek
<img src="urun1.jpg">
<img src="IMG_2931.jpg" alt="resim">

## İyi Örnek
<img src="oversize-keten-gomlek-erkek-mavi.jpg" alt="Erkek Oversize Keten Gömlek - Mavi, Yeni Sezon">

## Toplu Kontrol Script'i (Console'da çalıştırılabilir)
document.querySelectorAll('img:not([alt]), img[alt=""]').forEach(img => console.warn('Alt eksik:', img.src));

* Çoğu platformda (Shopify Ürün Düzenle → Görsel → Alt Text, WooCommerce Medya Kütüphanesi → Alternatif Metin) bu alan manuel doldurulur; toplu ürünlerde CSV ile toplu güncelleme yapılabilir.`;
}

function generateProductRichSnippet(siteInfo = {}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Product",
    "name": "{{Ürün Adı}}",
    "image": "{{Ürün Görseli URL}}",
    "description": "{{Ürün Açıklaması}}",
    "sku": "{{SKU}}",
    "brand": { "@type": "Brand", "name": siteInfo.title ? siteInfo.title.split(/[-|]/)[0].trim() : "{{Marka Adı}}" },
    "offers": {
      "@type": "Offer",
      "priceCurrency": "TRY",
      "price": "{{Fiyat}}",
      "availability": "https://schema.org/InStock",
      "url": siteInfo.url || "https://siteniz.com/urun/ornek"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.8",
      "reviewCount": "124"
    }
  };
  return `<!-- Google Zengin Sonuçlar (Rich Snippets) - Product Schema -->
<script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
</script>

* Ekledikten sonra Google "Rich Results Test" (search.google.com/test/rich-results) aracıyla doğrulayın. {{ }} içindeki alanları her ürün için dinamik doldurun (Shopify Liquid, WooCommerce PHP değişkenleri, Ticimax/İkas şablon etiketleri).`;
}

function generateSearchConsoleGuide(siteInfo = {}, platform = 'generic') {
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';
  const install = platformNote(platform, {
    shopify: 'Shopify: Online Store → Preferences → "Google Search Console" bölümünden HTML etiket doğrulamasını yapın veya DNS TXT kaydı ekleyin.',
    woocommerce: 'WooCommerce/WordPress: Yoast SEO / Rank Math eklentisindeki "Google Search Console doğrulama kodu" alanına yapıştırın.',
    ticimax: 'Ticimax: Yönetim Paneli → SEO Ayarları → Site Doğrulama Kodları bölümüne ekleyin.',
    ikas: 'İkas: Mağaza Ayarları → SEO → Arama Motoru Doğrulama alanına ekleyin.',
    generic: '<head> içine doğrulama meta etiketini elle ekleyin.'
  });

  return `# Google Search Console Kurulum Rehberi

1. https://search.google.com/search-console adresine gidip "URL öneki" ile ${domain} adresini ekleyin.
2. Doğrulama yöntemi olarak HTML meta etiketini seçin:
   <meta name="google-site-verification" content="{{DOĞRULAMA_KODU}}">
3. Kurulum notu (${platform || 'genel'}): ${install}
4. Doğrulama sonrası Sitemaps menüsünden sitemap.xml adresini gönderin: ${domain}/sitemap.xml
5. Coverage (Kapsam) raporunu haftalık kontrol ederek indekslenme hatalarını takip edin.`;
}

function generateAccessibilityGuide(siteInfo = {}, issues = []) {
  const issuesList = issues.length
    ? issues.map((i, idx) => `${idx + 1}. ${i}`).join('\n')
    : '1. Statik taramada kritik bulgu yok — renk kontrastı ve klavye gezinmesini manuel test edin.';

  return `# Erişilebilirlik (WCAG 2.1 AA) Düzeltme Rehberi

## Sitenizde Tespit Edilen Bulgular
${issuesList}

## Hızlı Düzeltme Kod Örnekleri

### 1. Form alanlarını etiketleyin
<label for="email">E-posta Adresi</label>
<input type="email" id="email" name="email">
<!-- veya -->
<input type="email" aria-label="E-posta Adresi">

### 2. Simge butonlara erişilebilir metin ekleyin
<button aria-label="Sepete Ekle">
  <svg>...</svg>
</button>

### 3. Sayfaya "İçeriğe Geç" linki ekleyin (en üste)
<a href="#main-content" class="skip-link">İçeriğe Geç</a>
...
<main id="main-content">...</main>

### 4. HTML dil niteliğini tanımlayın
<html lang="tr">

### 5. iframe'lere başlık ekleyin
<iframe src="..." title="Google Harita - Mağaza Konumu"></iframe>

## Manuel Kontrol Gerektiren Kriterler
- Renk kontrastı: Metin/arkaplan en az 4.5:1 oranında olmalı (araç: WebAIM Contrast Checker).
- Tüm sayfanın sadece klavye (Tab/Enter/Esc) ile kullanılabilir olduğunu test edin.
- Ekran okuyucu (VoiceOver/NVDA) ile checkout akışını uçtan uca deneyin.

* Not: WCAG 2.1 AA uyumluluğu artık birçok kurumsal ihale ve B2B tedarik sözleşmesinde zorunlu şart olarak aranıyor.`;
}

function generateCartFlowGuide() {
  return `<!-- Mini-Sepet (Cart Drawer) — Sepete Ekleyince Sayfa Yenilemeden Açılan Panel -->
<div class="precheck-cart-drawer" style="position:fixed;top:0;right:-360px;width:360px;height:100%;background:#fff;box-shadow:-4px 0 20px rgba(0,0,0,.15);transition:right .3s ease;z-index:9999;" data-cart-drawer>
  <div style="padding:16px;border-bottom:1px solid #eee;display:flex;justify-content:space-between;align-items:center;">
    <strong>Sepetim (<span class="cart-count">0</span>)</strong>
    <button onclick="document.querySelector('[data-cart-drawer]').style.right='-360px'">✕</button>
  </div>
  <div class="cart-items" style="padding:16px;"><!-- ürün satırları buraya --></div>
  <div style="padding:16px;border-top:1px solid #eee;">
    <a href="/sepet" style="display:block;text-align:center;padding:10px;background:#111;color:#fff;border-radius:8px;text-decoration:none;margin-bottom:8px;">Sepete Git</a>
    <a href="/checkout/guest" style="display:block;text-align:center;padding:10px;border:1px solid #ddd;border-radius:8px;text-decoration:none;color:#111;">Üye Olmadan Devam Et</a>
  </div>
</div>

<!-- Miktar Güncelleme (Quantity Stepper) -->
<div class="qty-selector" style="display:flex;align-items:center;gap:8px;">
  <button class="qty-minus" aria-label="Azalt">−</button>
  <input type="number" name="quantity" value="1" min="1" style="width:48px;text-align:center;">
  <button class="qty-plus" aria-label="Artır">+</button>
</div>

<script>
// "Sepete Ekle" tıklanınca drawer'ı aç (AJAX add-to-cart entegrasyonunuza bağlayın)
document.querySelectorAll('[class*="add-to-cart"]').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelector('[data-cart-drawer]').style.right = '0';
  });
});
</script>

## Kontrol Listesi
1. "Sepete Ekle" tıklanınca sayfa yenilenmeden (AJAX) mini-sepet açılmalı.
2. Sepette + / − ile miktar anında güncellenmeli (sayfa yenilemeden, toplam tutar canlı hesaplanmalı).
3. Checkout'a "Üye Olmadan Devam Et" seçeneği her zaman görünür olmalı.
4. Sepet ikonu header'da her sayfada sabit görünmeli ve içindeki ürün sayısını göstermeli.

* Not: Shopify/WooCommerce/Ticimax/İkas'ın çoğunda mini-sepet ve miktar güncelleme tema düzeyinde hazır gelir — genelde tema ayarlarından "Cart Drawer" veya "AJAX Cart" özelliğini açmanız yeterlidir.`;
}

function generateCheckoutSecurityGuide(siteInfo = {}) {
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';
  return `# Sipariş Tamamlama Güvenliği Rehberi

## 1. HTTPS Zorunluluğu
Tüm checkout/ödeme sayfalarının \`https://\` üzerinden servis edildiğinden emin olun. HTTP üzerinden kredi kartı bilgisi toplamak hem güvenlik riski hem de tarayıcılarda "Güvenli Değil" uyarısına yol açar.
\`\`\`
# Nginx örneği: HTTP -> HTTPS yönlendirme
server {
  listen 80;
  server_name ${domain.replace('https://', '').replace('http://', '')};
  return 301 https://$host$request_uri;
}
\`\`\`

## 2. Güven Rozeti / 3D Secure İbaresi
<div class="precheck-trust-badges" style="display:flex;gap:12px;align-items:center;margin:12px 0;">
  <img src="/assets/3d-secure.svg" alt="3D Secure ile Güvenli Ödeme" height="28">
  <img src="/assets/ssl-secure.svg" alt="SSL Güvenli Bağlantı" height="28">
  <span style="font-size:12px;color:#555;">🔒 256-bit SSL ile şifrelenmiş güvenli ödeme</span>
</div>

## 3. Anlaşılır Form Hata Mesajlaşması
<label for="card-number">Kart Numarası</label>
<input type="text" id="card-number" name="card_number" required aria-invalid="false" aria-describedby="card-number-error">
<span id="card-number-error" class="field-error" style="color:#d70015;font-size:12px;display:none;">Kart numarası 16 haneli olmalıdır.</span>

<script>
// Alan terk edildiğinde anlık doğrulama (sunucu cevabını beklemeden)
document.getElementById('card-number').addEventListener('blur', function() {
  const valid = /^\\d{16}$/.test(this.value.replace(/\\s/g, ''));
  document.getElementById('card-number-error').style.display = valid ? 'none' : 'block';
  this.setAttribute('aria-invalid', String(!valid));
});
</script>

## 4. Tanınan Bir Ödeme Altyapısı Kullanın
Kart bilgisini kendi sunucunuzda işlemek yerine PCI-DSS uyumlu bir sağlayıcı kullanın: **iyzico, PayTR, Param, Craftgate, Sipay** (Türkiye) veya **Stripe** (uluslararası). Bu hem güvenliği hem de müşteri güvenini artırır — ödeme formunda sağlayıcı logosunun görünür olması dönüşümü olumlu etkiler.

* Not: HTTPS eksikliği en kritik risktir — diğer tüm önlemler HTTPS olmadan anlamını yitirir.`;
}

function generateCheckoutFunnelGuide(siteInfo = {}, checkoutDetails = {}) {
  const flagged = checkoutDetails.flaggedFields || [];
  const flaggedList = flagged.length
    ? flagged.map((f, i) => `${i + 1}. "${f.field}" — ${f.reason}`).join('\n')
    : '1. Bu taramada gereksiz alan tespit edilmedi, yine de aşağıdaki genel kontrol listesini uygulayın.';

  const stepCount = checkoutDetails.detectedStepCount ?? '?';
  const totalFields = checkoutDetails.totalFields ?? '?';

  return `# Checkout Dönüşüm Optimizasyonu Rehberi

## Tespit Edilen Durum
- Adım sayısı: ${stepCount}
- Toplam form alanı: ${totalFields}
- Misafir checkout: ${checkoutDetails.hasGuestCheckout ? 'Mevcut ✅' : 'Bulunamadı ❌'}
- Zorunlu üyelik: ${checkoutDetails.forcesAccountCreation ? 'Tespit edildi ⚠️' : 'Yok ✅'}

## Kaldırılması/Opsiyonel Yapılması Önerilen Alanlar
${flaggedList}

## Genel Checkout Optimizasyon Kuralları
1. **Tek sayfa (one-page) checkout** kullanın veya adım sayısını 3'ün altında tutun: Sepet → Adres+Ödeme → Onay.
2. **İlerleme göstergesi** ekleyin ("Adım 2/3: Ödeme") — kullanıcı ne kadar kaldığını bilsin.
   <div class="checkout-steps" aria-label="Sipariş adımları">
     <span class="step active">1. Sepet</span>
     <span class="step">2. Teslimat</span>
     <span class="step">3. Ödeme</span>
   </div>
3. **Misafir (guest) checkout'u varsayılan yapın**, üyeliği sipariş sonrasına bırakın:
   <a href="/checkout/guest" class="btn-guest">Üye Olmadan Devam Et →</a>
4. **Otomatik adres/kart doldurma** için doğru autocomplete niteliklerini kullanın:
   <input type="text" name="address" autocomplete="street-address">
   <input type="tel" name="phone" autocomplete="tel">
5. **Hata mesajlarını alan bazında ve anında** gösterin (form gönderildikten sonra değil, kullanıcı alanı terk ettiğinde).
6. Ödeme adımında **toplam tutarı, kargo ücretini ve varsa vergiyi** her zaman görünür tutun — sürpriz maliyet en büyük terk nedenidir.

* Not: Her kaldırılan gereksiz form alanı ortalama %2-4 checkout tamamlama oranı artışı sağlayabilir (Baymard Institute araştırmaları).`;
}

function generateSitemapGuide(siteInfo = {}, platform = 'generic') {
  const domain = siteInfo.url ? new URL(siteInfo.url).origin : 'https://siteniz.com';
  const install = platformNote(platform, {
    shopify: 'Shopify sitemap.xml otomatik oluşturulur: ' + domain + '/sitemap.xml — genelde ek işlem gerekmez, sadece erişilebilir olduğunu doğrulayın.',
    woocommerce: 'WooCommerce/WordPress: Yoast SEO veya Rank Math eklentisi aktifse sitemap otomatik ' + domain + '/sitemap_index.xml adresinde oluşur.',
    ticimax: 'Ticimax: Panelde otomatik oluşturulur, SEO Ayarları → Site Haritası bölümünden URL\'i kontrol edin.',
    ikas: 'İkas: Otomatik oluşturulur; Mağaza Ayarları → SEO → Site Haritası bölümünden erişilebilirliği doğrulayın.',
    generic: 'Sitemap oluşturmuyorsa bir XML sitemap üretici eklentisi/kütüphanesi kullanın ve robots.txt içine referansını ekleyin.'
  });

  return `# sitemap.xml Kontrol & Kurulum Rehberi

1. ${domain}/sitemap.xml adresinin tarayıcıda açılıp geçerli XML döndürdüğünü doğrulayın.
2. Kurulum notu (${platform || 'genel'}): ${install}
3. robots.txt dosyanıza şu satırı ekleyin:
   Sitemap: ${domain}/sitemap.xml
4. Yeni ürün/kategori eklendiğinde sitemap'in otomatik güncellendiğinden emin olun (çoğu platformda otomatik).
5. Google Search Console → Sitemaps bölümünden gönderip "Success" durumunu kontrol edin.`;
}

module.exports = {
  generateLlmsTxt,
  generateRobotsTxt,
  generateFaqSchema,
  generateBreadcrumbSnippet,
  generateSocialMeta,
  generateStickyPhoneHtml,
  generateLegalTemplates,
  generate404Page,
  generateTopCtaBanner,
  generateInternalLinkingGuide,
  generateThankYouPageSnippet,
  generateCaseStudyBlock,
  generatePageSpeedGuide,
  generateMetaTitleGuide,
  generateMetaDescriptionGuide,
  generateFastAuthButtons,
  generateGoogleMapEmbed,
  generateReviewsWidget,
  generateImageAltGuide,
  generateProductRichSnippet,
  generateSearchConsoleGuide,
  generateSitemapGuide,
  generateAccessibilityGuide,
  generateCheckoutFunnelGuide,
  generateCartFlowGuide,
  generateCheckoutSecurityGuide
};
